"""
VerseBot for reddit
By Matthieu Grieger
books.py
Copyright (c) 2015 Matthieu Grieger (MIT License)
"""

def get_book(name):
    """ Retrieves a standardized book name to replace the one
    provided by the user. """
    
    books = {
        "genesis":"Genesis",  # Old Testament
        "gen":"Genesis",
        "gn":"Genesis",
        "bereshit":"Genesis",
        "exodus":"Exodus",
        "exod":"Exodus",
        "ex":"Exodus",
        "shemot":"Exodus",
        "leviticus":"Leviticus",
        "lev":"Leviticus",
        "lv":"Leviticus",
        "vayikra":"Leviticus",
        "numbers":"Numbers",
        "num":"Numbers",
        "nm":"Numbers",
        "bemidbar":"Numbers",
        "deuteronomy":"Deuteronomy",
        "deut":"Deuteronomy",
        "dt":"Deuteronomy",
        "devarim":"Deuteronomy",
        "joshua":"Joshua",
        "josh":"Joshua",
        "yehoshua":"Joshua",
        "judges":"Judges",
        "judg":"Judges",
        "jgs":"Judges",
        "shoftim":"Judges",
        "ruth":"Ruth",
        "ru":"Ruth",
        "1samuel":"1 Samuel",
        "1sam":"1 Samuel",
        "1sm":"1 Samuel",
        "1shmuel":"1 Samuel",
        "2samuel":"2 Samuel",
        "2sam":"2 Samuel",
        "2sm":"2 Samuel",
        "2shmuel":"2 Samuel",
        "1kings":"1 Kings",
        "1kgs":"1 Kings",
        "1melachim":"1 Kings",
        "2kings":"2 Kings",
        "2kgs":"2 Kings",
        "2melachim":"2 Kings",
        "1chronicles":"1 Chronicles",
        "1chron":"1 Chronicles",
        "1chr":"1 Chronicles",
        "2chronicles":"2 Chronicles",
        "2chron":"2 Chronicles",
        "2chr":"2 Chronicles",
        "ezra":"Ezra",
        "ezr":"Ezra",
        "nehemiah":"Nehemiah",
        "neh":"Nehemiah",
        "esther":"Esther",
        "est":"Esther",
        "job":"Job",
        "jb":"Job",
        "psalms":"Psalms",
        "psalm":"Psalms",
        "ps":"Psalms",
        "pss":"Psalms",
        "proverbs":"Proverbs",
        "prov":"Proverbs",
        "prv":"Proverbs",
        "ecclesiastes":"Ecclesiastes",
        "eccles":"Ecclesiastes",
        "eccl":"Ecclesiastes",
        "songofsolomon":"Song of Songs",
        "songofsongs":"Song of Songs",
        "songofsol":"Song of Songs",
        "sg":"Song of Songs",
        "isaiah":"Isaiah",
        "isa":"Isaiah",
        "yeshayahu":"Isaiah",
        "yeshaya":"Isaiah",
        "jeremiah":"Jeremiah",
        "jer":"Jeremiah",
        "yirmiyahu":"Jeremiah",
        "yirmiyah":"Jeremiah",
        "lamentations":"Lamentations",
        "lam":"Lamentations",
        "ezekiel":"Ezekiel",
        "ezek":"Ezekiel",
        "yechezkel":"Ezekiel",
        "daniel":"Daniel",
        "dan":"Daniel",
        "dn":"Daniel",
        "hosea":"Hosea",
        "hos":"Hosea",
        "hoshea":"Hosea",
        "joel":"Joel",
        "jl":"Joel",
        "yoel":"Joel",
        "amos":"Amos",
        "am":"Amos",
        "obadiah":"Obadiah",
        "obad":"Obadiah",
        "ob":"Obadiah",
        "ovadiah":"Obadiah",
        "ovadyah":"Obadiah",
        "jonah":"Jonah",
        "jon":"Jonah",
        "micah":"Micah",
        "mic":"Micah",
        "michah":"Micah",
        "nahum":"Nahum",
        "nah":"Nahum",
        "na":"Nahum",
        "nachum":"Nahum",
        "habakkuk":"Habakkuk",
        "hab":"Habakkuk",
        "hb":"Habakkuk",
        "chavakuk":"Habakkuk",
        "zephaniah":"Zephaniah",
        "zeph":"Zephaniah",
        "zep":"Zephaniah",
        "tzefaniah":"Zephaniah",
        "tzefanyah":"Zephaniah",
        "haggai":"Haggai",
        "hag":"Haggai",
        "hg":"Haggai",
        "chaggai":"Haggai",
        "zechariah":"Zechariah",
        "zech":"Zechariah",
        "zec":"Zechariah",
        "zecharya":"Zechariah",
        "zecharyah":"Zechariah",
        "zechariyah":"Zechariah",
        "malachi":"Malachi",
        "mal":"Malachi",
        "matthew":"Matthew",  # New Testament
        "mathew":"Matthew",
        "matt":"Matthew",
        "mat":"Matthew",
        "mt":"Matthew",
        "mark":"Mark",
        "mk":"Mark",
        "luke":"Luke",
        "lk":"Luke",
        "john":"John",
        "jn":"John",
        "acts":"Acts",
        "actsoftheapostles":"Acts",
        "romans":"Romans",
        "rom":"Romans",
        "1corinthians":"1 Corinthians",
        "1cor":"1 Corinthians",
        "2corinthians":"2 Corinthians",
        "2cor":"2 Corinthians",
        "galatians":"Galatians",
        "gal":"Galatians",
        "ephesians":"Ephesians",
        "eph":"Ephesians",
        "philippians":"Philippians",
        "phil":"Philippians",
        "colossians":"Colossians",
        "col":"Colossians",
        "1thessalonians":"1 Thessalonians",
        "1thess":"1 Thessalonians",
        "1thes":"1 Thessalonians",
        "2thessalonians":"2 Thessalonians",
        "2thess":"2 Thessalonians",
        "2thes":"2 Thessalonians",
        "1timothy":"1 Timothy",
        "1tim":"1 Timothy",
        "1tm":"1 Timothy",
        "2timothy":"2 Timothy",
        "2tim":"2 Timothy",
        "2tm":"2 Timothy",
        "titus":"Titus",
        "ti":"Titus",
        "philemon":"Philemon",
        "philem":"Philemon",
        "phlm":"Philemon",
        "hebrews":"Hebrews",
        "heb":"Hebrews",
        "james":"James",
        "jas":"James",
        "1peter":"1 Peter",
        "1pet":"1 Peter",
        "1pt":"1 Peter",
        "2peter":"2 Peter",
        "2pet":"2 Peter",
        "2pt":"2 Peter",
        "1john":"1 John",
        "1jn":"1 John",
        "2john":"2 John",
        "2jn":"2 John",
        "3john":"3 John",
        "3jn":"3 John",
        "jude":"Jude",
        "revelation":"Revelation",
        "revelations":"Revelation",
        "rev":"Revelation",
        "rv":"Revelation",
        "judith":"Judith",  # Deuterocanon
        "judeth":"Judith",
        "jdt":"Judith",
        "wisdom":"Wisdom",
        "wis":"Wisdom",
        "wisdomofsolomon":"Wisdom",
        "tobit":"Tobit",
        "tob":"Tobit",
        "sirach":"Ecclesiasticus",
        "sir":"Ecclesiasticus",
        "ecclesiasticus":"Ecclesiasticus",
        "baruch":"Baruch",
        "bar":"Baruch",
        "1maccabees":"1 Maccabees",
        "1macc":"1 Maccabees",
        "1mac":"1 Maccabees",
        "2maccabees":"2 Maccabees",
        "2macc":"2 Maccabees",
        "2mac":"2 Maccabees",
        "3maccabees":"3 Maccabees",
        "3macc":"3 Maccabees",
        "3mac":"3 Maccabees",
        "4maccabees":"4 Maccabees",
        "4macc":"4 Maccabees",
        "4mac":"4 Maccabees",
        "restofdaniel":"Prayer of Azariah",
        "additionstodaniel":"Prayer of Azariah",
        "adddan":"Prayer of Azariah",
        "songofthethreechildren":"Prayer of Azariah",
        "prayerofazariah":"Prayer of Azariah",
        "restofesther":"Additions to Esther",
        "additionstoesther":"Additions to Esther",
        "addesth":"Additions to Esther",
        "prayerofmanasses":"Prayer of Manasseh",
        "prayerofmanasseh":"Prayer of Manasseh",
        "manasses":"Prayer of Manasseh",
        "manasseh":"Prayer of Manasseh",
        "prman":"Prayer of Manasseh",
        "1esdras":"1 Esdras",
        "1esd":"1 Esdras",
        "2esdras":"2 Esdras",
        "2esd":"2 Esdras",
        "storyofsusanna":"Susanna",
        "susanna":"Susanna",
        "sus":"Susanna",
        "belandthedragon":"Bel and the Dragon",
        "bel":"Bel and the Dragon"
    }
    
    try:
        converted_name = books[name.lower().replace(" ", "")]
        return converted_name
    except KeyError:
        return None
        
def get_book_number(book_name):
    """ Find appropriate book number for book name. This is used in
    situations where local bibles are used, or to determine if a translation
    supports a book (mostly the deuterocanon). """
    
    book_numbers = {
        "Genesis":1,
        "Exodus":2,
        "Leviticus":3,
        "Numbers":4,
        "Deuteronomy":5,
        "Joshua":6,
        "Judges":7,
        "Ruth":8,
        "1 Samuel":9,
        "2 Samuel":10,
        "1 Kings":11,
        "2 Kings":12,
        "1 Chronicles":13,
        "2 Chronicles":14,
        "Ezra":15,
        "Nehemiah":16,
        "Esther":17,
        "Job":18,
        "Psalms":19,
        "Proverbs":20,
        "Ecclesiastes":21,
        "Song of Songs":22,
        "Isaiah":23,
        "Jeremiah":24,
        "Lamentations":25,
        "Ezekiel":26,
        "Daniel":27,
        "Hosea":28,
        "Joel":29,
        "Amos":30,
        "Obadiah":31,
        "Jonah":32,
        "Micah":33,
        "Nahum":34,
        "Habakkuk":35,
        "Zephaniah":36,
        "Haggai":37,
        "Zechariah":38,
        "Malachi":39,
        "Matthew":40,
        "Mark":41,
        "Luke":42,
        "John":43,
        "Acts":44,
        "Romans":45,
        "1 Corinthians":46,
        "2 Corinthians":47,
        "Galatians":48,
        "Ephesians":49,
        "Philippians":50,
        "Colossians":51,
        "1 Thessalonians":52,
        "2 Thessalonians":53,
        "1 Timothy":54,
        "2 Timothy":55,
        "Titus":56,
        "Philemon":57,
        "Hebrews":58,
        "James":59,
        "1 Peter":60,
        "2 Peter":61,
        "1 John":62,
        "2 John":63,
        "3 John":64,
        "Jude":65,
        "Revelation":66,
        "Judith":67,
        "Wisdom":68,
        "Tobit":69,
        "Ecclesiasticus":70,
        "Baruch":71,
        "1 Maccabees":72,
        "2 Maccabees":73,
        "3 Maccabees":74,
        "4 Maccabees":75,
        "Prayer of Azariah":76,
        "Additions to Esther":77,
        "Prayer of Manasseh":78,
        "1 Esdras":79,
        "2 Esdras":80,
        "Susanna":81,
        "Bel and the Dragon":82
    }
    
    try:
        book_number = book_numbers[book_name]
        return book_number
    except KeyError:
        return None
        
def get_tanakh_name(book_name):
    """ Retrieves the book name used in TaggedTanakh URLs. """
    
    tanakh_names = {
        "Genesis":"Gen",
        "Exodus":"Exod",
        "Leviticus":"Lev",
        "Numbers":"Num",
        "Deuteronomy":"Deut",
        "Joshua":"Josh",
        "Judges":"Judg",
        "1 Samuel":"1%20Sam",
        "2 Samuel":"2%20Sam",
        "1 Kings":"1%20Kings",
        "2 Kings":"2%20Kings",
        "Isaiah":"Isa",
        "Jeremiah":"Jer",
        "Ezekiel":"Ezek",
        "Hosea":"Hosea",
        "Joel":"Joel",
        "Amos":"Amos",
        "Obadiah":"Obad",
        "Jonah":"Jon",
        "Micah":"Mic",
        "Nahum":"Nah",
        "Habakkuk":"Hab",
        "Zephaniah":"Zeph",
        "Haggai":"Hag",
        "Zechariah":"Zech",
        "Malachi":"Mal",
        "Psalms":"Ps",
        "Proverbs":"Prov",
        "Job":"Job",
        "Song of Songs":"Songs",
        "Ruth":"Ruth",
        "Lamentations":"Lam",
        "Ecclesiastes":"Eccles",
        "Esther":"Esther",
        "Daniel":"Dan",
        "Ezra":"Ezra",
        "Nehemiah":"Neh",
        "1 Chronicles":"1%20Chron",
        "2 Chronicles":"2%20Chron"
    }
    
    return tanakh_names[book_name]
